language: r
cache: packages
r: 
  - bioc-release
  - bioc-devel
git:
  # To only get latest commit
  depth: 1
warnings_are_errors: true
r_packages:
  - roxygen2

install:
  - R -e 'devtools::install_deps(dep = T)'
  - R 'e 'install.packages('roxygen2')'
  # so namespace is up-to-date
  - R -e 'devtools::document(roclets=c('rd', 'collate', 'namespace'))'

script:
  - R CMD build .
  - R CMD check *tar.gz
  - R CMD BiocCheck *tar.gz
