language: r
cache: packages
r: 
  - bioc-release
  - bioc-devel
git:
  # To only get latest commit
  depth: 1
warnings_are_errors: true
sudo: required

# faster install
r_binary_packages:
  - devtools
r_packages:
  - roxygen2
bioc_packages:
  - BiocCheck
  
before_script:
  # so NAMESPACE is up-to-date
  - R -e 'devtools::document(roclets=c("rd", "collate", "namespace"))'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  # BiocCheck
  - R CMD BiocCheck *tar.gz
