language: r
cache: packages
r: 
  - bioc-release
  - bioc-devel
git:
  # To only get latest commit
  depth: 1
warnings_are_errors: true
sudo: required

bioc_packages:
  - BiocCheck
  
script:
  - R -e 'devtools::check(document=TRUE, cran=FALSE, force_suggests=TRUE)'

after_success:
  # BiocCheck
  - R CMD BiocCheck *tar.gz
